### ISSUE TITLE
Create subdomain DM for material auxiliary and derived fields.

### ISSUE THREAD

**Issue by baagaard-usgs** [geodynamics/pylith#83]
Create subdomain DM for use with material auxiliary and derived fields. Use `DMPlexFilter()`.

This will significant reduce overhead in sections for domains with several materials, because the chart will span just the cells of the material, not the entire domain.

**Comment by baagaard-usgs** [comment]
**PyLith branch**: baagaard/feature-material-subdm

**Comment by baagaard-usgs** [comment]
**PETSC branch**: knepley/pylith
**PyLith branch**: baagaard/feature-material-subdm

**Unit test fails**: Creating section with submesh created by createSubmesh() with basis order 0, quad order 0, dimension 2 for Hex/Tet meshes results in a section with DOF at faces and edges instead of just faces.

```
cd unittests/libtests/meshio
make check
```

Look at `testvtk.log`:
```
pylith::meshio::TestDataWriterVTKSubmesh_Hex::testWriteCellField
DM Object: domain (domain_) 1 MPI processes
  type: plex
domain in 2 dimensions:
  Cells are at height 1
Supports:
[0] Max support size: 3
[0]: 2 ----> 10
[0]: 2 ----> 13
[0]: 3 ----> 12
[0]: 3 ----> 13
[0]: 4 ----> 10
[0]: 4 ----> 11
[0]: 4 ----> 14
[0]: 5 ----> 11
[0]: 5 ----> 12
[0]: 5 ----> 16
[0]: 6 ----> 14
[0]: 6 ----> 15
[0]: 7 ----> 15
[0]: 7 ----> 16
[0]: 8 ----> 0
[0]: 9 ----> 1
[0]: 10 ----> 8
[0]: 11 ----> 8
[0]: 11 ----> 9
[0]: 12 ----> 8
[0]: 13 ----> 8
[0]: 14 ----> 9
[0]: 15 ----> 9
[0]: 16 ----> 9
Cones:
[0] Max cone size: 6
[0]: 0 <---- 8 (0)    [Brad: face 8 hangs off cell 0]]
[0]: 1 <---- 9 (0)    [Brad: face 9 hangs off cell 1]
[0]: 8 <---- 10 (0)    [Brad: face 8 has edges 10, 11, 12, 13]
[0]: 8 <---- 11 (0)
[0]: 8 <---- 12 (0)
[0]: 8 <---- 13 (0)
[0]: 9 <---- 14 (0)    [Brad: face 9 has edges 14, 15, 16, 11]
[0]: 9 <---- 15 (0)
[0]: 9 <---- 16 (0)
[0]: 9 <---- 11 (-2)
[0]: 10 <---- 2 (0)    [Brad: edge 10 has vertices 2, 4]
[0]: 10 <---- 4 (0)
[0]: 11 <---- 4 (0)    [Brad: edge 11 has vertices 4, 5]
[0]: 11 <---- 5 (0)
[0]: 12 <---- 5 (0)    [Brad: edge 12 has vertices 5, 3]
[0]: 12 <---- 3 (0)
[0]: 13 <---- 3 (0)    [Brad: edge 13 has vertices 3, 2]
[0]: 13 <---- 2 (0)
[0]: 14 <---- 4 (0)   [Brad: edge 14 has vertices 4, 6]
[0]: 14 <---- 6 (0)
[0]: 15 <---- 6 (0)   [Brad: edge 15 has vertices 6, 7]
[0]: 15 <---- 7 (0)
[0]: 16 <---- 7 (0)   [Brad: edge 16 has vertices 7, 5]
[0]: 16 <---- 5 (0)
coordinates with 1 fields
  field 0 with 3 components
Process 0:
  (   2) dim  3 offset   0 -0.1 -0.1 0.1
  (   3) dim  3 offset   3 -0.1 0.1 0.1
  (   4) dim  3 offset   6 0. -0.1 0.1
  (   5) dim  3 offset   9 0. 0.1 0.1
  (   6) dim  3 offset  12 0.1 -0.1 0.1
  (   7) dim  3 offset  15 0.1 0.1 0.1
Viewing field 'scalar' setField().
  Subfields:
    Subfield scalar, index: 0, components: scalar, scale: 1, basisOrder: 0, quadOrder: 0, dimension: 2
  dimensionalize flag: 0
DM Object: 1 MPI processes
  type: plex
DM_0x55b14e3babe0_244 in 2 dimensions:
  Cells are at height 1
  0-cells: 6
  1-cells: 7
  2-cells: 2
Labels:
  depth: 4 strata with value/size (0 (6), 1 (7), 2 (2), 3 (2))
Field scalar:
  adjacency FEM
PetscSection Object: 1 MPI processes
  type not yet set
1 fields
  field 0 with 1 components
Process 0:
  (   0) dim  0 offset   0
  (   1) dim  0 offset   0
  (   2) dim  0 offset   0
  (   3) dim  0 offset   0
  (   4) dim  0 offset   0
  (   5) dim  0 offset   0
  (   6) dim  0 offset   0
  (   7) dim  0 offset   0
  (   8) dim  1 offset   0    [Brad: faces 8-9]
  (   9) dim  1 offset   1
  (  10) dim  1 offset   2    [Brad: edges 10-16] 
  (  11) dim  1 offset   3
  (  12) dim  1 offset   4
  (  13) dim  1 offset   5
  (  14) dim  1 offset   6
  (  15) dim  1 offset   7
  (  16) dim  1 offset   8
```

Test report:
```
1) test: pylith::meshio::TestDataWriterVTKSubmesh_Hex::testWriteCellField (F) line: 211 /home/brad/src/cig/pylith/unittests/libtests/meshio/FieldFactory.cc
equality assertion failed
- Expected: 2
- Actual  : 9   [Brad: 2 faces + 7 edges]


2) test: pylith::meshio::TestDataWriterVTKSubmesh_Tet::testWriteCellField (F) line: 211 /home/brad/src/cig/pylith/unittests/libtests/meshio/FieldFactory.cc
equality assertion failed
- Expected: 2
- Actual  : 7 [Brad: 2 faces + 5 edges]
```

**Comment by knepley** [comment]
I think this is a problem with the layout engine for vtkHeight > 0.

**Comment by knepley** [comment]
Its not producing testvtk.log for me.

**Comment by baagaard-usgs** [comment]
Note: I merged baagaard/feature-material-subdm into knepley/feature-petsc-fe.

If you have an older automake, then the test may just generate a single log file (not sure of the name). Newer versions of automake allow use of multiple threads to run tests simultaneously and puts the output from each test in $TEST.log and the combined results in test-suite.log.

**Comment by knepley** [comment]
This is now fixed in knepley/pylith. The new error seems to be that the cell field is not named "pressure"

**Comment by baagaard-usgs** [comment]
I still get the same original errors for the VTK tests using the current knepley/pylith and knepley/feature-petsc-fe.

**Comment by knepley** [comment]
Here is the fix:
https://bitbucket.org/petsc/petsc/commits/3fd2e703412ffcd292ca078ffb74b1b269831408?at=knepley/fix-plex-layout-submesh
Bitbucket shows it as being in knepley/pylith. Do you have it?

**Comment by baagaard-usgs** [comment]
Pulled. Fix verified. Test data updated. Tests in unittests/meshio now pass!
